package view;

/**
 *
 * @author PC
 */
public class QLTOURView extends javax.swing.JFrame {

    /**
     * Creates new form QLTOURVIEW
     */
    public QLTOURView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chbDHCongNghiep = new javax.swing.JCheckBox();
        chbQuocGia = new javax.swing.JCheckBox();
        chbThuongMai = new javax.swing.JCheckBox();
        chbSuPham = new javax.swing.JCheckBox();
        chbHaNoi = new javax.swing.JCheckBox();
        chbThuyLoi = new javax.swing.JCheckBox();
        chbGTVT = new javax.swing.JCheckBox();
        chbBaoChi = new javax.swing.JCheckBox();
        chbNganHang = new javax.swing.JCheckBox();
        chbY = new javax.swing.JCheckBox();
        chbFPT = new javax.swing.JCheckBox();
        chbRMIT = new javax.swing.JCheckBox();
        chbKTQD = new javax.swing.JCheckBox();
        chbXayDung = new javax.swing.JCheckBox();
        chbBachKhoa = new javax.swing.JCheckBox();
        chbKHTN = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        cboDiaDiemDaChon = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnKhongThem = new javax.swing.JButton();
        btnThemTour = new javax.swing.JButton();
        chbALL = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dvgDSTour = new javax.swing.JTable();
        btnHuyTour = new javax.swing.JButton();
        btnDatTour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tra cứu thông tin Tour"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setText("TRA CỨU THÔNG TOUR THAM QUAN CÁC TRƯỜNG ĐẠI HỌC");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chọn các địa điểm đi qua:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N

        chbDHCongNghiep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbDHCongNghiep.setText("ĐH Công Nghiệp");
        chbDHCongNghiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbDHCongNghiepActionPerformed(evt);
            }
        });

        chbQuocGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbQuocGia.setText("ĐH Quốc Gia");
        chbQuocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbQuocGiaActionPerformed(evt);
            }
        });

        chbThuongMai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbThuongMai.setText("ĐH Thương Mại");
        chbThuongMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbThuongMaiActionPerformed(evt);
            }
        });

        chbSuPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbSuPham.setText("ĐH Sư Phạm");
        chbSuPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbSuPhamActionPerformed(evt);
            }
        });

        chbHaNoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbHaNoi.setText("ĐH Hà Nội");
        chbHaNoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbHaNoiActionPerformed(evt);
            }
        });

        chbThuyLoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbThuyLoi.setText("ĐH Thủy Lợi");
        chbThuyLoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbThuyLoiActionPerformed(evt);
            }
        });

        chbGTVT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbGTVT.setText("ĐH GTVT");
        chbGTVT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbGTVTActionPerformed(evt);
            }
        });

        chbBaoChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbBaoChi.setText("HV Báo Chí");
        chbBaoChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbBaoChiActionPerformed(evt);
            }
        });

        chbNganHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbNganHang.setText("HV Ngân Hàng");
        chbNganHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbNganHangActionPerformed(evt);
            }
        });

        chbY.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbY.setText("ĐH Y");
        chbY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbYActionPerformed(evt);
            }
        });

        chbFPT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbFPT.setText("ĐH FPT");
        chbFPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbFPTActionPerformed(evt);
            }
        });

        chbRMIT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbRMIT.setText("ĐH RMIT");
        chbRMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbRMITActionPerformed(evt);
            }
        });

        chbKTQD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbKTQD.setText("ĐH KTQD");
        chbKTQD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbKTQDActionPerformed(evt);
            }
        });

        chbXayDung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbXayDung.setText("ĐH Xây Dựng");
        chbXayDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbXayDungActionPerformed(evt);
            }
        });

        chbBachKhoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbBachKhoa.setText("ĐH Bách Khoa");
        chbBachKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbBachKhoaActionPerformed(evt);
            }
        });

        chbKHTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbKHTN.setText("ĐH KHTN");
        chbKHTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbKHTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chbDHCongNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbThuongMai, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbQuocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbSuPham, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chbKHTN, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbBachKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbXayDung, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbKTQD, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chbRMIT, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbY, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbNganHang, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbFPT, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chbBaoChi, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbGTVT, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbThuyLoi, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbHaNoi, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbDHCongNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbThuongMai, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbQuocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbSuPham, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbBaoChi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbGTVT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbThuyLoi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbHaNoi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbKHTN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbBachKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbXayDung, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbKTQD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbRMIT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbY, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbNganHang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbFPT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tùy chọn:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(485, 347));

        cboDiaDiemDaChon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboDiaDiemDaChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDiaDiemDaChonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Bạn có muốn xem gợi ý về Tour hành trinhg không?");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Bắt đầu từ:");

        btnKhongThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKhongThem.setText("No");
        btnKhongThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhongThemActionPerformed(evt);
            }
        });

        btnThemTour.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThemTour.setText("YES");
        btnThemTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTourActionPerformed(evt);
            }
        });

        chbALL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbALLActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Chọn tất cả:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnKhongThem, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbALL, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDiaDiemDaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbALL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboDiaDiemDaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKhongThem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bẳng hiển thị thông tin Tour:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N

        dvgDSTour.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dvgDSTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tour", "Hành Trình", "Số Địa Điểm", "Tổng Quãng Đường"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dvgDSTour);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1309, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnHuyTour.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHuyTour.setText("Hủy Tour");
        btnHuyTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyTourActionPerformed(evt);
            }
        });

        btnDatTour.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDatTour.setText("Đặt Tour");
        btnDatTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatTourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(626, 626, 626)
                        .addComponent(btnDatTour, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHuyTour, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHuyTour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDatTour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbDHCongNghiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbDHCongNghiepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbDHCongNghiepActionPerformed

    private void chbThuongMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbThuongMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbThuongMaiActionPerformed

    private void chbQuocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbQuocGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbQuocGiaActionPerformed

    private void chbSuPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbSuPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbSuPhamActionPerformed

    private void chbBaoChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbBaoChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbBaoChiActionPerformed

    private void chbGTVTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbGTVTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbGTVTActionPerformed

    private void chbThuyLoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbThuyLoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbThuyLoiActionPerformed

    private void chbHaNoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbHaNoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbHaNoiActionPerformed

    private void chbKHTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbKHTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbKHTNActionPerformed

    private void chbBachKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbBachKhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbBachKhoaActionPerformed

    private void chbXayDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbXayDungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbXayDungActionPerformed

    private void chbKTQDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbKTQDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbKTQDActionPerformed

    private void chbRMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbRMITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbRMITActionPerformed

    private void chbYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbYActionPerformed

    private void chbNganHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbNganHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbNganHangActionPerformed

    private void chbFPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbFPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbFPTActionPerformed

    private void chbALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbALLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbALLActionPerformed

    private void cboDiaDiemDaChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDiaDiemDaChonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiaDiemDaChonActionPerformed

    private void btnThemTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemTourActionPerformed

    private void btnKhongThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhongThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKhongThemActionPerformed

    private void btnDatTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatTourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDatTourActionPerformed

    private void btnHuyTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyTourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyTourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLTOURView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLTOURView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLTOURView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLTOURView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLTOURView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatTour;
    private javax.swing.JButton btnHuyTour;
    private javax.swing.JButton btnKhongThem;
    private javax.swing.JButton btnThemTour;
    private javax.swing.JComboBox<String> cboDiaDiemDaChon;
    private javax.swing.JCheckBox chbALL;
    private javax.swing.JCheckBox chbBachKhoa;
    private javax.swing.JCheckBox chbBaoChi;
    private javax.swing.JCheckBox chbDHCongNghiep;
    private javax.swing.JCheckBox chbFPT;
    private javax.swing.JCheckBox chbGTVT;
    private javax.swing.JCheckBox chbHaNoi;
    private javax.swing.JCheckBox chbKHTN;
    private javax.swing.JCheckBox chbKTQD;
    private javax.swing.JCheckBox chbNganHang;
    private javax.swing.JCheckBox chbQuocGia;
    private javax.swing.JCheckBox chbRMIT;
    private javax.swing.JCheckBox chbSuPham;
    private javax.swing.JCheckBox chbThuongMai;
    private javax.swing.JCheckBox chbThuyLoi;
    private javax.swing.JCheckBox chbXayDung;
    private javax.swing.JCheckBox chbY;
    private javax.swing.JTable dvgDSTour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
