/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bt_nguoi_du_lich.Data.Form;

import bt_nguoi_du_lich.Data.FileController;
import bt_nguoi_du_lich.Data.Location;
import bt_nguoi_du_lich.Data.Person;
import bt_nguoi_du_lich.Data.Tour;
import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.List;
import java.util.Scanner;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thanh
 */
/*
0, 374, 200, 223, 108, 178, 252, 285, 240, 356, 215, 171, 301, 98, 141
374, 0, 255, 166, 433, 199, 135, 95, 136, 17, 272, 112, 324, 132, 89
200, 255, 0, 128, 277, 128, 180, 160, 131, 247, 129, 223, 28, 81, 245
223, 166, 128, 0, 430, 47, 52, 84, 40, 155, 75, 133, 219, 109, 310
108, 433, 277, 430, 0, 453, 478, 344, 389, 423, 355, 284, 99, 111, 176
178, 199, 128, 47, 453, 0, 91, 110, 64, 181, 291, 53, 319, 190, 85
252, 135, 180, 52, 478, 91, 0, 114, 83, 117, 401, 222, 113, 261, 183
285, 95, 160, 84, 344, 110, 114, 0, 47, 78, 299, 232, 154, 169, 117
240, 136, 131, 40, 389, 64, 83, 47, 0, 118, 71, 124, 101, 276, 123
356, 17, 247, 155, 423, 181, 117, 78, 118, 0, 81, 193, 221, 145, 98
215, 272, 129, 75, 355, 291, 401, 299, 71, 81, 0, 410, 311, 167, 159
171, 112, 223, 133, 284, 53, 222, 232, 124, 193, 410, 0, 51, 174, 327
301, 324, 28, 219, 99, 319, 113, 154, 101, 221, 311, 51, 0, 77, 192
98, 132, 81, 109, 111, 190, 261, 169, 276, 145, 167, 174, 77, 0, 219
141, 89, 245, 310, 176, 85, 183, 117, 123, 98, 159, 327, 192, 219, 0

*/
public class NguoiDuLichForm extends javax.swing.JFrame {

    /**
     * Creates new form NguoiDuLichForm
     */
    public static int [][] trongSo= FileController.ArrayTrongSo("TrongSo.txt");
    
    public static int [][] TrongSoSetting= new int [trongSo.length][trongSo.length];
    static List<Location> locations=null;
    static List<Location> locationSetting= null;
    
    private int numberOfNodes;
    public static DefaultTableModel model;

    public NguoiDuLichForm() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        locationSetting= new ArrayList<>();
        locations= FileController.getAllLocation("Location.txt");
        model = (DefaultTableModel)tbTour.getModel();
//        for(Tour tour : )

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inpName = new javax.swing.JTextField();
        inpAddress = new javax.swing.JTextField();
        inpPhone = new javax.swing.JTextField();
        btnFindPerson = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        checkNhaThoLon = new javax.swing.JCheckBox();
        checkLangBac = new javax.swing.JCheckBox();
        checkPhoCo = new javax.swing.JCheckBox();
        checkNhaTu = new javax.swing.JCheckBox();
        checkVanMieu = new javax.swing.JCheckBox();
        checkGaHaNoi = new javax.swing.JCheckBox();
        checkCauLongBien = new javax.swing.JCheckBox();
        checkNhaHatLon = new javax.swing.JCheckBox();
        checkChuaMotCot = new javax.swing.JCheckBox();
        checkHTTL = new javax.swing.JCheckBox();
        checkNuiTram = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        checkHoGuom = new javax.swing.JCheckBox();
        checkHoTay = new javax.swing.JCheckBox();
        checkChoDX = new javax.swing.JCheckBox();
        checkCotCoHaNoi = new javax.swing.JCheckBox();
        btnAccept = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtStart = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEnd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTour = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(64, 64, 64));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setToolTipText("0");

        jLabel3.setText("Nhập họ tên:");

        jLabel1.setText("Nhập địa chỉ:");

        jLabel4.setText("Nhập số điện thoại:");

        inpAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpAddressActionPerformed(evt);
            }
        });

        btnFindPerson.setText("Find");
        btnFindPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindPersonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nhập thông tin của bạn");

        btnContinue.setText("Continue");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inpName)
                            .addComponent(inpAddress)
                            .addComponent(inpPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnFindPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inpPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(inpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1))
                            .addComponent(inpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindPerson)
                    .addComponent(btnContinue))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setEnabled(false);

        jLabel5.setText("Ðiểm xuất phát:");

        checkNhaThoLon.setText("Nhà thờ lớn");
        checkNhaThoLon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNhaThoLonActionPerformed(evt);
            }
        });

        checkLangBac.setText("Lăng Bác");
        checkLangBac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLangBacActionPerformed(evt);
            }
        });

        checkPhoCo.setText("Phố Cổ");
        checkPhoCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPhoCoActionPerformed(evt);
            }
        });

        checkNhaTu.setText("Nhà tù Hỏa Lò");
        checkNhaTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNhaTuActionPerformed(evt);
            }
        });

        checkVanMieu.setText("Văn Miếu");
        checkVanMieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVanMieuActionPerformed(evt);
            }
        });

        checkGaHaNoi.setText("Ga Hà Nội");
        checkGaHaNoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGaHaNoiActionPerformed(evt);
            }
        });

        checkCauLongBien.setText("Cầu Lòng Biên");
        checkCauLongBien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCauLongBienActionPerformed(evt);
            }
        });

        checkNhaHatLon.setText("Nhà hát lớn");
        checkNhaHatLon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNhaHatLonActionPerformed(evt);
            }
        });

        checkChuaMotCot.setText("Chùa Một Cột");
        checkChuaMotCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkChuaMotCotActionPerformed(evt);
            }
        });

        checkHTTL.setText("HT Thăng Long");
        checkHTTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHTTLActionPerformed(evt);
            }
        });

        checkNuiTram.setText("Núi Trầm");
        checkNuiTram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNuiTramActionPerformed(evt);
            }
        });

        jLabel6.setText("Chọn các địa điểm muốn đi qua:");

        checkHoGuom.setText("Hồ Gươm");
        checkHoGuom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHoGuomActionPerformed(evt);
            }
        });

        checkHoTay.setText("Hồ Tây");
        checkHoTay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHoTayActionPerformed(evt);
            }
        });

        checkChoDX.setText("Chợ Đồng Xuân");
        checkChoDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkChoDXActionPerformed(evt);
            }
        });

        checkCotCoHaNoi.setText("Cột cờ Hà Nội");
        checkCotCoHaNoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCotCoHaNoiActionPerformed(evt);
            }
        });

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Chọn lịch trình của bạn");

        txtStart.setEditable(false);
        txtStart.setEnabled(false);
        txtStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartActionPerformed(evt);
            }
        });

        jLabel9.setText("Ðiểm cuối cùng");

        txtEnd.setEditable(false);
        txtEnd.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnClear)
                        .addGap(38, 38, 38)
                        .addComponent(btnDelete))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(checkChuaMotCot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(checkHTTL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(checkHoGuom, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 9, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(checkNuiTram, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkVanMieu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(checkNhaHatLon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkCauLongBien))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(checkLangBac, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkNhaThoLon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkPhoCo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkGaHaNoi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkNhaTu))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkHoTay, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkChoDX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkCotCoHaNoi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(checkNhaThoLon)
                                .addComponent(checkLangBac)
                                .addComponent(checkHoGuom))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(checkChuaMotCot)
                                .addComponent(checkNuiTram)
                                .addComponent(checkVanMieu))
                            .addGap(20, 20, 20)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checkNhaHatLon)
                                    .addComponent(checkCauLongBien))
                                .addComponent(checkHTTL)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(checkHoTay)
                            .addGap(18, 18, 18)
                            .addComponent(checkChoDX)
                            .addGap(20, 20, 20)
                            .addComponent(checkCotCoHaNoi)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(checkNhaTu)
                        .addGap(18, 18, 18)
                        .addComponent(checkPhoCo)
                        .addGap(20, 20, 20)
                        .addComponent(checkGaHaNoi)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(btnClear)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        tbTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdTour", "Họ tên", "Chu trình", "Tổng chi phí", "Số địa điểm"
            }
        ));
        tbTour.setRowHeight(50);
        jScrollPane1.setViewportView(tbTour);
        if (tbTour.getColumnModel().getColumnCount() > 0) {
            tbTour.getColumnModel().getColumn(0).setHeaderValue("IdTour");
            tbTour.getColumnModel().getColumn(1).setHeaderValue("Họ tên");
            tbTour.getColumnModel().getColumn(2).setMinWidth(500);
            tbTour.getColumnModel().getColumn(2).setHeaderValue("Chu trình");
            tbTour.getColumnModel().getColumn(3).setHeaderValue("Tổng chi phí");
            tbTour.getColumnModel().getColumn(4).setHeaderValue("Số địa điểm");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inpAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpAddressActionPerformed

    private void generateValue(int ii, String name) {
        int index= locationSetting.size();
        locationSetting.add(new Location(ii, name, index));
        if (locationSetting.size()>1){
            for (int i=0; i<locationSetting.size(); i++){
                TrongSoSetting[index][i]= trongSo[ii][locationSetting.get(i).getIdLocation()];
                TrongSoSetting[i][index]= trongSo[ii][locationSetting.get(i).getIdLocation()];
            }
        }
        txtStart.setText(locationSetting.get(0).getNameLoaction());
        txtStart.setEnabled(true);
        txtEnd.setText(locationSetting.get(locationSetting.size()-1).getNameLoaction());
        txtEnd.setEnabled(true);

    }
    //Tim duong di ngan nhat
    public static int n;
    public static int[][] c = new int[100][100];
    public static int[] x = new int[100];
    public static int[] chuaxet = new int[100];
    public static int[] kq = new int[100];
    public static int MIN = 0;
    public static int a = 1;
    
    public static void Init() {
        n = locationSetting.size();
        for (int i = 1; i <= n; i++) {
            for (int j = 1; j <= n; j++) {
                c[i][j] = TrongSoSetting[i-1][j-1];
                    
            }
        }
        x[1] = 1;
        for (int i = 2; i <= n; i++) {
            chuaxet[i] = 1;
        }
    }
    
    public static void Result() {
        System.out.println("Ma tran:");
        for (int i = 0; i <= n; i++) {
            for (int j = 0; j <= n; j++) {
                System.out.print(c[i][j] + " ");
            }
            System.out.println("");
        }
        System.out.print("\n T1=>");
        for (int i = 2; i <= n; i++) {
            System.out.print("T");
            System.out.print(kq[i]);
            System.out.print("=>");
        }
        System.out.print("T1");
        System.out.print("\n Chi phi cua hanh trinh la: ");
        System.out.print(MIN);
    }
    
    public static void Work() {
        int S = 0;
        for (int i = 1; i <= n - 1; i++) {
            S = S + c[x[i]][x[i + 1]];
        }
        S = S + c[x[n]][1];
        if (S < MIN || a == 1) {
            a = 0;
            MIN = S;
            for (int i = 1; i <= n; i++) {
                kq[i] = x[i];
            }
        }
    }

    public static void Try(int i) {
        for (int j = 2; j <= n; j++) {
            if (chuaxet[j] != 0) {
                x[i] = j;
                chuaxet[j] = 0;
                if (i == n) {
                    Work();
                } else {
                    Try(i + 1);
                }
                chuaxet[j] = 1;
            }
        }
    }
    private void action(){
        Init();
        Try(2);
        Result();
    }
    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        try{
            for (int i=0; i<locationSetting.size(); i++){
            for (int j=0; j<locationSetting.size(); j++){
                System.out.print(TrongSoSetting[i][j]+" ");
            }
            System.out.println("");
        }
        System.out.println("===============================================");
        action();
        System.out.println("ARRAY KETQUA: ");
        ArrayList<Location> kqLocation = new ArrayList<>();
        for(int i = 1; i <= locationSetting.size(); i++){
            kqLocation.add(locationSetting.get(kq[i]-1));
        }
        kqLocation.add(locationSetting.get(0));
        Location []way = new Location[kqLocation.size()];
        for(int i = 0; i < way.length; i++){
            way[i] = kqLocation.get(i);
        }
        for(Location lct : way){
            System.out.println(lct.getNameLoaction());
        }
        int idPerson = 1;
        int idTour = 1;
        String name = inpName.getText();
        String dc = inpAddress.getText();
        String sdt = inpPhone.getText();
        Person ps = new Person(idPerson++, name, dc, sdt);
        String lctStart = txtStart.getText().trim();
        Location Start = new Location();
        
        for(Location lct : locations){
            if(lct.getNameLoaction().trim().equals(lctStart)){
                Start = lct;
            }
        }
        Tour tour = new Tour(idTour, ps, Start, way , MIN);
        idTour++;
        model.addRow(new Object[]{
            tour.getId(), ps.getName(), tour.outputWay(), tour.getCost(), locationSetting.size()
        });
        
        Person person = new Person(idPerson++, name, dc, sdt);
        FileController.writeTourFile("Tour.txt", tour);
        FileController.writePersonFile("Person.txt", person);
        System.out.println(tour);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Bạn phải lựa chọn các thành phố muốn đi qua" + ex.getMessage());
        }
                
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnFindPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindPersonActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinueActionPerformed

    private void checkHoGuomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHoGuomActionPerformed
        generateValue(0, "Hồ Gươm");
    }//GEN-LAST:event_checkHoGuomActionPerformed

    private void checkLangBacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLangBacActionPerformed
        generateValue(1, "Lăng Bác");
    }//GEN-LAST:event_checkLangBacActionPerformed

    private void checkNhaThoLonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNhaThoLonActionPerformed
        generateValue(2, "Nhà Thờ");
    }//GEN-LAST:event_checkNhaThoLonActionPerformed

    private void checkNhaTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNhaTuActionPerformed
        generateValue(3, "Nhà tù hỏa lò");
    }//GEN-LAST:event_checkNhaTuActionPerformed

    private void checkHoTayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHoTayActionPerformed
        generateValue(4, "Hồ tây");
    }//GEN-LAST:event_checkHoTayActionPerformed

    private void checkChuaMotCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkChuaMotCotActionPerformed
        generateValue(5, "Chùa một cột");
    }//GEN-LAST:event_checkChuaMotCotActionPerformed

    private void checkNuiTramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNuiTramActionPerformed
        generateValue(6, "Núi trầm");
    }//GEN-LAST:event_checkNuiTramActionPerformed

    private void checkVanMieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVanMieuActionPerformed
        generateValue(7, "Văn miếu");
    }//GEN-LAST:event_checkVanMieuActionPerformed

    private void checkPhoCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPhoCoActionPerformed
        generateValue(8, "Phố cổ");
    }//GEN-LAST:event_checkPhoCoActionPerformed

    private void checkChoDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkChoDXActionPerformed
        generateValue(9, "Chợ đồng xuân");
    }//GEN-LAST:event_checkChoDXActionPerformed

    private void checkHTTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHTTLActionPerformed
        generateValue(10, "HT Thăng Long");
    }//GEN-LAST:event_checkHTTLActionPerformed

    private void checkNhaHatLonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNhaHatLonActionPerformed
        generateValue(11, "Nhà hát lớn");
    }//GEN-LAST:event_checkNhaHatLonActionPerformed

    private void checkCauLongBienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCauLongBienActionPerformed
        generateValue(12, "Cầu Long Biên");
    }//GEN-LAST:event_checkCauLongBienActionPerformed

    private void checkGaHaNoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGaHaNoiActionPerformed
        generateValue(13, "Ga Hà Nội");
    }//GEN-LAST:event_checkGaHaNoiActionPerformed

    private void checkCotCoHaNoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCotCoHaNoiActionPerformed
        generateValue(14, "Cột cờ Hà Nội");
    }//GEN-LAST:event_checkCotCoHaNoiActionPerformed
    private void ClearLocation(){
        checkCauLongBien.setSelected(false);
        checkChoDX.setSelected(false);
        checkChuaMotCot.setSelected(false);
        checkCotCoHaNoi.setSelected(false);
        checkGaHaNoi.setSelected(false);
        checkHTTL.setSelected(false);
        checkHoGuom.setSelected(false);
        checkHoTay.setSelected(false);
        checkLangBac.setSelected(false);
        checkNhaHatLon.setSelected(false);
        checkNhaThoLon.setSelected(false);
        checkNuiTram.setSelected(false);
        checkNhaTu.setSelected(false);
        checkPhoCo.setSelected(false);
        checkVanMieu.setSelected(false);
        txtEnd.setText("");
        txtStart.setText("");
        txtEnd.setEnabled(false);
        txtStart.setEnabled(false);
        locationSetting.clear();
    }
    private void ClearPerson(){
        inpName.setText("");
        inpAddress.setText("");
        inpPhone.setText("");
    }
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        ClearLocation();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NguoiDuLichForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NguoiDuLichForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NguoiDuLichForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NguoiDuLichForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NguoiDuLichForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFindPerson;
    private javax.swing.JCheckBox checkCauLongBien;
    private javax.swing.JCheckBox checkChoDX;
    private javax.swing.JCheckBox checkChuaMotCot;
    private javax.swing.JCheckBox checkCotCoHaNoi;
    private javax.swing.JCheckBox checkGaHaNoi;
    private javax.swing.JCheckBox checkHTTL;
    private javax.swing.JCheckBox checkHoGuom;
    private javax.swing.JCheckBox checkHoTay;
    private javax.swing.JCheckBox checkLangBac;
    private javax.swing.JCheckBox checkNhaHatLon;
    private javax.swing.JCheckBox checkNhaThoLon;
    private javax.swing.JCheckBox checkNhaTu;
    private javax.swing.JCheckBox checkNuiTram;
    private javax.swing.JCheckBox checkPhoCo;
    private javax.swing.JCheckBox checkVanMieu;
    private javax.swing.JTextField inpAddress;
    private javax.swing.JTextField inpName;
    private javax.swing.JTextField inpPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTour;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtStart;
    // End of variables declaration//GEN-END:variables

//    private void showComboLocation() {
//        List<Location> locations = FileController.getAllLocation("Location.txt");
//        for(Location item : locations){
//            cbStart.addItem(item.getNameLoaction());
//        }
//    }
    
    

//    private void timDuongDi() {
//        int number_of_nodes= locationSetting.size();
//        try
//        {
//            number_of_nodes = locationSetting.size()-1;
//            for(int i = 1; i <= number_of_nodes; i++){
//                for(int j = 1; j <= number_of_nodes; j++){
//                    if(TrongSoSetting[i][j] == 1 && TrongSoSetting[j][i] == 0){
//                        TrongSoSetting[j][i] = 1;
//                    }
//                }
//            }
//            System.out.println("the citys are visited as follows");
//            tsp(TrongSoSetting);
//        } catch (InputMismatchException inputMismatch)
//         {
//             System.out.println("Wrong Input format");
//         }
//    }
    
//    public void tsp(int adjacencyMatrix[][])
//    {
//        numberOfNodes = adjacencyMatrix[1].length - 1;
//        int[] visited = new int[numberOfNodes + 1];
//        visited[1] = 1;
//        stack.push(1);
//        int element, dst = 0, i;
//        int min = Integer.MAX_VALUE;
//        boolean minFlag = false;
//        System.out.print(1 + "\t");
//
//        while (!stack.isEmpty())
//        {
//            element = stack.peek();
//            i = 1;
//            min = Integer.MAX_VALUE;
//            while (i <= numberOfNodes)
//            {
//                if (adjacencyMatrix[element][i] > 1 && visited[i] == 0)
//                {
//                    if (min > adjacencyMatrix[element][i])
//                    {
//                        min = adjacencyMatrix[element][i];
//                        dst = i;
//                        minFlag = true;
//                    }
//                }
//                i++;
//            }
//            if (minFlag)
//            {
//                visited[dst] = 1;
//                stack.push(dst);
//                System.out.print(dst + "\t");
//                minFlag = false;
//                continue;
//            }
//            stack.pop();
//        }
//    }
}
